### ISSUE TITLE
A ajouter au construit du restore pour qu'il teste la connexion

### ISSUE THREAD

**Issue by PierCase** [maltyxx/diablosql#1]
// Tentative de connexion à la base avec les données renseignées
        $mysqli = new mysqli($config['host'], $config['user'], $config['password'], $config['database']);
        if ($mysqli->connect_error)
            \Travis\CLI::fatal("Impossible de se connecter à la base {$config['versus']}");

**Comment by maltyxx** [comment]
C'est corrigé, merci
