### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by PierCase** [maltyxx/diablosql#2]
Le programme essaie d'exécuter la commande suivante lors du backup : 
nohup sh -c "/usr/bin/mysqldump --host='host' --user='user' --password='password''"

cela ne fonctionne pas sur ma machine (j'ai un access denied for user...) alors que si j'exécute directement :  

/usr/bin/mysqldump --host='host' --user='user' --password='password' 

je ne rencontre pas de problème, une idée ? 

merci,

**Comment by PierCase** [comment]
Pour être plus précis : 

cette commande ne fonctionne pas : 
nohup sh -c "/usr/bin/mysqldump --host='xxx' --user='xxx' --password='xxx' --quick --skip-lock-tables --result-file='/tmp/diablo/backup/gmb/address.sql' gmb address" > /dev/null 2>&1 & echo $!

alors que celle-ci fonctionne sur ma vagrant

sudo /usr/bin/mysqldump --host='xxx' --user='xxx' --password='xxx' --quick --skip-lock-tables --result-file='/tmp/diablo/backup/gmb/address.sql' gmb address

**Comment by maltyxx** [comment]
Vérifiez vos droits sur le répertoire /tmp/diablo/backup/gmb/

**Comment by PierCase** [comment]
Même avec les droits 777 j'ai toujours le problème

**Comment by PierCase** [comment]
Ok c'était à cause des caractères spéciaux dans le mot de passe : $ <...
mais c'est dommage qu'on ne puisse pas les mettre
